# Essential services for AppFlowy Cloud

services:
  appflowycloud:
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FEATURES: ""
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 12
    image: appflowyinc/appflowycloud:${APPFLOWY_CLOUD_VERSION:-latest}
    ports:
      - 6080:6080
      - 80:80