services:
  appflowycloud:
    restart: on-failure
    environment:
      - RUST_LOG=debug
      - APPFLOWY_ENVIRONMENT=production
      - APPFLOWY_DATABASE_URL=postgres://postgres:password@appflowycloud:5432/postgres
      - APPFLOWY_REDIS_URI=redis://appflowycloud:6379
      - APPFLOWY_GOTRUE_JWT_SECRET=hello456
      - APPFLOWY_GOTRUE_JWT_EXP=7200
      - APPFLOWY_GOTRUE_BASE_URL=http://appflowycloud:9999
      - APPFLOWY_GOTRUE_EXT_URL=http://localhost/gotrue
      - APPFLOWY_GOTRUE_ADMIN_EMAIL=admin@example.com
      - APPFLOWY_GOTRUE_ADMIN_PASSWORD=password
      - APPFLOWY_S3_CREATE_BUCKET=true
      - APPFLOWY_S3_USE_MINIO=true
      - APPFLOWY_S3_MINIO_URL=http://appflowycloud:9000
      - APPFLOWY_S3_ACCESS_KEY=minioadmin
      - APPFLOWY_S3_SECRET_KEY=minioadmin
      - APPFLOWY_S3_BUCKET=appflowy
      - APPFLOWY_S3_REGION=
      - APPFLOWY_S3_PRESIGNED_URL_ENDPOINT=
      - APPFLOWY_MAILER_SMTP_HOST=smtp.gmail.com
      - APPFLOWY_MAILER_SMTP_PORT=465
      - APPFLOWY_MAILER_SMTP_USERNAME=email_sender@some_company.com
      - APPFLOWY_MAILER_SMTP_EMAIL=email_sender@some_company.com
      - APPFLOWY_MAILER_SMTP_PASSWORD=email_sender_password
      - APPFLOWY_MAILER_SMTP_TLS_KIND=wrapper
      - APPFLOWY_ACCESS_CONTROL=true
      - APPFLOWY_DATABASE_MAX_CONNECTIONS=40
      - AI_SERVER_HOST=ai
      - AI_SERVER_PORT=5001
      - AI_OPENAI_API_KEY=
      - APPFLOWY_ADMIN_FRONTEND_PATH_PREFIX=/console
      - APPFLOWY_WEB_URL=http://localhost
      - ENV_DISPLAY_WIDTH=
      - ENV_DISPLAY_HEIGHT=
      - SUPABASE_PASSWORD=root
      - GOTRUE_ADMIN_EMAIL=admin@example.com
      - GOTRUE_ADMIN_PASSWORD=password
      - GOTRUE_DISABLE_SIGNUP=false
      - GOTRUE_SITE_URL=appflowy-flutter://
      - GOTRUE_URI_ALLOW_LIST=**
      - GOTRUE_JWT_SECRET=hello456
      - GOTRUE_JWT_EXP=7200
      - GOTRUE_JWT_ADMIN_GROUP_NAME=supabase_admin
      - GOTRUE_DB_DRIVER=postgres
      - API_EXTERNAL_URL=http://localhost/gotrue
      - DATABASE_URL=postgres://supabase_auth_admin:root@appflowycloud:5432/postgres
      - GOTRUE_SMTP_HOST=smtp.gmail.com
      - GOTRUE_SMTP_PORT=465
      - GOTRUE_SMTP_USER=email_sender@some_company.com
      - GOTRUE_SMTP_PASS=email_sender_password
      - GOTRUE_MAILER_URLPATHS_CONFIRMATION=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_INVITE=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_RECOVERY=/gotrue/verify
      - GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE=/gotrue/verify
      - GOTRUE_MAILER_TEMPLATES_MAGIC_LINK=
      - GOTRUE_SMTP_ADMIN_EMAIL=comp_admin@some_company.com
      - GOTRUE_SMTP_MAX_FREQUENCY=1ns
      - GOTRUE_RATE_LIMIT_EMAIL_SENT=100
      - GOTRUE_MAILER_AUTOCONFIRM=true
      - GOTRUE_EXTERNAL_GOOGLE_ENABLED=false
      - GOTRUE_EXTERNAL_GOOGLE_CLIENT_ID=
      - GOTRUE_EXTERNAL_GOOGLE_SECRET=
      - GOTRUE_EXTERNAL_GOOGLE_REDIRECT_URI=http://localhost/gotrue/callback
      - GOTRUE_EXTERNAL_GITHUB_ENABLED=false
      - GOTRUE_EXTERNAL_GITHUB_CLIENT_ID=
      - GOTRUE_EXTERNAL_GITHUB_SECRET=
      - GOTRUE_EXTERNAL_GITHUB_REDIRECT_URI=http://localhost/gotrue/callback
      - GOTRUE_EXTERNAL_DISCORD_ENABLED=false
      - GOTRUE_EXTERNAL_DISCORD_CLIENT_ID=
      - GOTRUE_EXTERNAL_DISCORD_SECRET=
      - GOTRUE_EXTERNAL_DISCORD_REDIRECT_URI=http://localhost/gotrue/callback
      - GOTRUE_SAML_ENABLED=false
      - GOTRUE_SAML_PRIVATE_KEY=
      - APPFLOWY_WORKER_REDIS_URL=redis://appflowycloud:6379
      - APPFLOWY_WORKER_ENVIRONMENT=production
      - APPFLOWY_WORKER_DATABASE_URL=postgres://postgres:password@appflowycloud:5432/postgres
      - APPFLOWY_WORKER_DATABASE_NAME=postgres
      - APPFLOWY_WORKER_IMPORT_TICK_INTERVAL=30
      - MINIO_BROWSER_REDIRECT_URL=http://localhost/minio
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - ADMIN_FRONTEND_HOST=appflowycloud
      - ADMIN_FRONTEND_PORT=4000
      - ADMIN_FRONTEND_REDIS_URL=redis://appflowycloud:6379
      - ADMIN_FRONTEND_GOTRUE_URL=http://appflowycloud:9999
      - ADMIN_FRONTEND_APPFLOWY_CLOUD_URL=http://appflowycloud:8000
      - ADMIN_FRONTEND_PATH_PREFIX=/console
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FEATURES: ""
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 5s
      timeout: 5s
      retries: 12
    image: appflowyinc/appflowycloud:latest
    ports:
      - 6080:6080
      - 80:80 